name: Validate package version

description: |
  Ensures that the version of package.json in pull request is updated compared to main.

inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Validate package.json version update
      shell: bash
      run: |
        set -e

        PACKAGE_JSON="package.json"

        if [ ! -f "$PACKAGE_JSON" ]; then
          echo "No package.json found at repo root. Skipping."
          exit 0
        fi

        BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
        WORKDIR="${{ inputs.working-directory }}"
        MAIN_VERSION=$(git show "origin/$BASE_BRANCH:$WORKDIR/$PACKAGE_JSON" | jq -r '.version')
        PR_VERSION=$(jq -r '.version' "$PACKAGE_JSON")

        echo "Main version: $MAIN_VERSION"
        echo "PR version: $PR_VERSION"

        if ! npx semver -r ">$MAIN_VERSION" "$PR_VERSION" > /dev/null; then
          echo "❌ package.json version ($PR_VERSION) must be greater than main ($MAIN_VERSION)!"
          exit 1
        fi

        echo "✅ package.json version updated."
      working-directory: ${{ inputs.working-directory }}
