name: Run Tests

description: |
  This action runs the tests using npm.
  
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: npm run test --if-present -- --watchAll=false
      working-directory: ${{ inputs.working-directory }}
