name: Setup Node.js

description: |
  This action sets up Node.js with the specified version.

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: '18'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}