name: Build App

description: |
  This action builds the application using npm.

runs:
  using: "composite"
  steps:
    - name: Clean npm cache and build app
      shell: bash
      run: |
        rm -rf node_modules/.cache
        npm cache clean --force
        npm install
        npm run build