name: Setup Python
description: Sets up a Python environment with a specified version

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}