name: Detect Direct Pushes to Main

on:
  push:
    branches:
      - 'main'

jobs:
  detect-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Direct Push
        uses: ./actions/version-control/detect-direct-push