name: Validate Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  detect-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Validate VERSION and CHANGELOG
        uses: ./actions/general/validate-version-changelog/action.yml@main